### ISSUE TITLE
extruding plastic

### ISSUE THREAD

**Issue by zumpchke** [yoavmil/amlib#1]
Where are the parts for extruding plastic?

**Comment by yoavmil** [comment]
what do you mean? what are you looking for?

**Comment by zumpchke** [comment]
I have a 2D path 0.4mm thick that I want to extrude. However, there are 100e3 points so slicer struggles. I was wondering whether I could write something that outputs gcode directly since I already know the toolpath, but I'm not sure how to control the extruder stepper.

**Comment by yoavmil** [comment]
`amlib` maybe helpful. But you'll need to write the gcode writer yourself, which is fairly simple.
